name: Create Image Slideshow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  slideshow:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Create GIF slideshow
        run: |
          convert \
          -delay 150 \
          -loop 0 \
          assets/image1.jpg \
          assets/image2.jpg \
          assets/japan-slideshow.gif

      - name: Commit GIF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/japan-slideshow.gif

          git commit -m "Generate Japan slideshow GIF" || echo "No changes"

          git pull --rebase origin main

          git push origin main
